### PR TITLE
Remove deprecated symbols from master branch

### LINKED ISSUE #1088: Remove deprecated symbols from master branch
#### Description of Problem:

OpenSCAP API contains a very large amount of deprecated symbols.
If we remove them before we release 1.3.0-alpha1, we will be able to detect soon if the removal causes any problem.

This could be very useful in modern Linux distributions if they will contain 1.3.0-alpha1. They will be able to detect possible problems with integration of other components that depend on OpenSCAP API.

#### OpenSCAP Version:
current upstream master HEAD

#### Operating System & Version:
every

#### Steps to Reproduce:

1. open the header files
2. 
3. 

#### Actual Results:

OpenSCAP API contains deprecated symbols

#### Expected Results:

OpenSCAP API doesn't contain deprecated symbols

#### Additional Information / Debugging Steps:

nothing

### PR DESCRIPTION
**Pull request by jan-cerny**
In this PR I have removed deprecated symbols from master branch.

For further details and detailed description of the specific changes, please read the commit messages of the specific commit.

Fixes #1088

### CODE REVIEW

File: src/CPE/cpelang.c [hunk 1]
```diff
@@ -125,11 +114,6 @@ char *cpe_lang_model_detect_version_priv(xmlTextReader *reader)
 	return oscap_strdup("2.3");
 }
 
-char * cpe_lang_model_detect_version(const char* file)
-{
-	return cpe_lang_model_detect_version_priv(NULL);
```
Comment (mpreisler) [inline src/CPE/cpelang.c]: why not also remove the function above, is anything using it?

Comment (jan-cerny) [reply src/CPE/cpelang.c]: cpe_lang_model_detect_version_priv is used only at src/source/oscap_source.c:387. It could be replaced by its code. On the other hand, it is a private function. I would prefer to define this string as a constant in some of the header files.

**Comment by jan-cerny** [comment]
AppVeyor failed! https://ci.appveyor.com/project/OpenSCAP/openscap/build/master-98

**Comment by jan-cerny** [comment]
AppVeyor is now OK! https://ci.appveyor.com/project/OpenSCAP/openscap/build/master-99
Resolved in 332983b.

**Comment by jan-cerny** [comment]
I am going to check if some of the deprecated symbols are used in Workbench and OSCAP Anaconda Addon

**Comment by jan-cerny** [comment]
I have verified that SCAP Workbench builds and runs with OpenSCAP built from the code in this PR.
