### PR TITLE
Fix realloc calls to account for a possible NULL result

### LINKED ISSUE #974: Check if realloc fails
We often forget to check for failure of `realloc()`. That is a minor issue, but it causes coverity issues.

Example:

```
1. openscap-1.2.16/src/SCE/sce_engine.c:482: error[memleakOnRealloc]: Common realloc mistake: 'env_values' nulled but not freed upon failure 
1. openscap-1.2.16/src/SCE/sce_engine.c:410: error[memleakOnRealloc]: Common realloc mistake: 'env_values' nulled but not freed upon failure 
1. openscap-1.2.16/src/OVAL/probes/unix/xinetd.c:1463: error[memleakOnRealloc]: Common realloc mistake: 'newstr_array' nulled but not freed upon failure 
1. openscap-1.2.16/src/OVAL/probes/unix/xinetd.c:1384: error[memleakOnRealloc]: Common realloc mistake: 'string_array' nulled but not freed upon failure 
 1. openscap-1.2.16/src/OVAL/probes/probe/main.c:110: error[memleakOnRealloc]: Common realloc mistake: '___G_no_varref_ents' nulled but not freed upon failure 
```
Please check all `realloc` occurrences.

### PR DESCRIPTION
**Pull request by evgenyz**
And clean up the old handle wherever deems necessary.

While I tried to mitigate improper `realloc` handling this patch won't bring much to memory management of the project. The only real benefit: it will prevent some memory leaks under memory pressure.

The whole approach of the project is to crash and burn when memory could not be allocated. It seems to be stemming from the Linux idea of overcommitting allocator, where checks of the result of the `malloc` are futile and the whole end-game of memory hungry application is OOM onslaught. 

Windows (for example) does not have this behaviour, and even Linux's allocator could be configured to behave differently (`ulimit`, `cgroups` you name it). But for proper memory handling in these scenarios one would have to fix *all* memory allocations, and it is a huge effort given the size of the cursed code-base.

Fixes #974, but only formally. It is just a dent on memory management problems.

### CODE REVIEW

File: src/OVAL/probes/SEAP/sexp-manip.c [hunk 1]
```diff
@@ -1564,8 +1579,12 @@ SEXP_t *SEXP_lstack_pop (SEXP_lstack_t *stack)
         }
 
         return (ref);
-resize:
-	stack->l_sref = realloc(stack->l_sref, sizeof(SEXP_t *) * stack->l_size);
+resize: ; // Yes, this is an empty statement. Only statements can be labeled
```
Comment (jan-cerny) [inline src/OVAL/probes/SEAP/sexp-manip.c:1582]: Thanks, I learned something new!

File: src/OVAL/probes/probe/icache.c [hunk 2]
```diff
@@ -129,7 +129,13 @@ static int icache_lookup(rbt_t *tree, int64_t item_id, probe_iqpair_t *pair) {
 		*/
 		dD("cache MISS");
 
-		cached->item = realloc(cached->item, sizeof(SEXP_t *) * ++cached->count);
+		void *new_item = realloc(cached->item, sizeof(SEXP_t *) * (cached->count+1));
```
Comment (jan-cerny) [inline src/OVAL/probes/probe/icache.c:132]:
```suggestion
		void *new_item = realloc(cached->item, sizeof(SEXP_t *) * (cached->count + 1));
```

File: src/OVAL/probes/unix/xinetd_probe.c [hunk 3]
```diff
@@ -1477,7 +1501,9 @@ int op_remove_strl(void *var, char *val)
 	newstr_array[newstr_array_size] = NULL;
 	free(string_array);
 	free(valstr_array);
-	newstr_array = realloc(newstr_array, sizeof(char*) * (newstr_array_size + 1));
+	void *new_newstr_array = realloc(newstr_array, sizeof(char*) * (newstr_array_size + 1));
```
Comment (jan-cerny) [inline src/OVAL/probes/unix/xinetd_probe.c:1504]:
```suggestion
	void *new_newstr_array = realloc(newstr_array, sizeof(char *) * (newstr_array_size + 1));
```

**Review by jan-cerny — COMMENTED** [review]
@evgenyz Looks great!

File: src/OVAL/probes/independent/textfilecontent54_probe.c [hunk 4]
```diff
@@ -173,7 +173,13 @@ static int process_file(const char *prefix, const char *path, const char *file,
 
 	do {
 		buf_size += buf_inc;
-		buf = realloc(buf, buf_size);
+		void *new_buf = realloc(buf, buf_size);
+		if (new_buf == NULL) {
+			dE("Can't re-allocate memory");
```
[the remark this answers is not in the document]
Comment (evgenyz) [reply src/OVAL/probes/independent/textfilecontent54_probe.c:178]: Well, `dE` should add the details. Or I'm missing something?

[the remark this answers is not in the document]
Comment (jan-cerny) [reply src/OVAL/probes/independent/textfilecontent54_probe.c:178]: aha ok

**Comment by evgenyz** [comment]
Fixed.

File: src/OVAL/probes/SEAP/sexp-manip.c [hunk 5]
```diff
@@ -1421,7 +1424,13 @@ SEXP_t *SEXP_list_sort(SEXP_t *list, int(*compare)(const SEXP_t *, const SEXP_t
                            list_it_alloc, list_it_alloc + SEXP_LISTIT_ARRAY_INC);
 
                         list_it_alloc += SEXP_LISTIT_ARRAY_INC;
-			list_it = realloc(list_it, sizeof(SEXP_list_it) * list_it_alloc);
+                        void *new_list_it = realloc(list_it, sizeof(SEXP_list_it) * list_it_alloc);
```
Comment (jan-cerny) [inline src/OVAL/probes/SEAP/sexp-manip.c:1427]: @evgenyz `new_list_it` probably should be assigned to `list_it`.

Comment (evgenyz) [reply src/OVAL/probes/SEAP/sexp-manip.c:1427]: Yes, it should. Thanks.
