### PR TITLE
Small fixes in "oscap xccdf generate fix", mostly for Ansible

### LINKED ISSUE #1112: Fix profile titles in generated ansible roles
#### Description of Problem:
When there are newlines in profile title there are no commentary marks for these newlines in the generated ansible role headers. This results in an invalid generated ansible roles.

#### Steps to Reproduce:
To reproduce you need to build older version of SSG (tested with `0.1.36`) which has one such a profile title. The role with the issue is `ssg-rhel6-role-nist-cl-il-al.yml`.

This issue is also reported in [RHBZ#1548499](https://bugzilla.redhat.com/show_bug.cgi?id=1548499) and can be fixed in a simillar way as the profile description was fixed in the PR #838.

### PR DESCRIPTION
**Pull request by jan-cerny**
* Fixes variables indentation. As we use 2 spaces to indent our content, the variables
which are on second level of indentation, should use 4 spaces.
* Handles multiline profile tittles and descriptions. Multiline titles were handled at all (See issue #1112). The code is improved to strip the whitespaces.
* Replaces `--template` by `--fix-type` in Playbook header. Using `--fix-type` is more understandable and it's easier for users than using the URN namespace.

 Fixes #1112.

### CODE REVIEW

**Comment by jan-cerny** [comment]
Hi @ggbecker @matejak @matusmarhefka @yuumasato @dahaic . Is there any volunteer to review?

File: src/XCCDF_POLICY/xccdf_policy_remediate.c [hunk 1]
```diff
@@ -802,6 +802,57 @@ static int _xccdf_item_recursive_gather_selected_rules(struct xccdf_policy *poli
 	return ret;
 }
 
+static char *_comment_multiline_text(char *text)
```
Comment (matejak) [inline src/XCCDF_POLICY/xccdf_policy_remediate.c]: Please split this function into smaller functions - it is somehow mind-bending to guess the intent of the code.

Unfortunately, we don't have easy unit-test support, so please include a comment indicating what the functions is supposed to do - it may not be obvious outside of the context of this PR.

File: src/XCCDF_POLICY/xccdf_policy_remediate.c [hunk 2]
```diff
@@ -802,6 +802,57 @@ static int _xccdf_item_recursive_gather_selected_rules(struct xccdf_policy *poli
...
+		return oscap_strdup("Not available");
+	}
+	const char *filler = "\n# ";
+	size_t buffer_size = strlen(text) + 1; // +1 for terminating '\0'
+	char *buffer = malloc(buffer_size);
+	char *saveptr, *str;
+	size_t filler_len = strlen(filler);
+	size_t result_len = 0;
+	bool first = true;
+	for (str = text; ; str = NULL) {
```
Comment (matejak) [inline src/XCCDF_POLICY/xccdf_policy_remediate.c]: The `for` condition is somehow mind-bending.

File: src/XCCDF_POLICY/xccdf_policy_remediate.c [hunk 3]
```diff
@@ -802,6 +802,57 @@ static int _xccdf_item_recursive_gather_selected_rules(struct xccdf_policy *poli
...
+		char *token = oscap_strtok_r(str, "\n", &saveptr);
+		if (token == NULL) {
+			break;
+		}
+		while (isspace(*token)) {
+			token++;
+		}
+		size_t token_len = strlen(token);
+		if (token_len > 0) {
```
Comment (matejak) [inline src/XCCDF_POLICY/xccdf_policy_remediate.c]: This is a good candidate for a function for extraction.

File: src/XCCDF_POLICY/xccdf_policy_remediate.c [hunk 4]
```diff
@@ -802,6 +802,57 @@ static int _xccdf_item_recursive_gather_selected_rules(struct xccdf_policy *poli
...
+			char *token_last_char = token + token_len - 1;
+			while(isspace(*token_last_char)) {
+				token_last_char--;
+			}
+			*(token_last_char + 1) = '\0';
+			token_len = strlen(token);
+		}
+		if (token_len > 0) {
```
Comment (matejak) [inline src/XCCDF_POLICY/xccdf_policy_remediate.c]: This is also a good candidate for a function for extraction.

File: src/XCCDF_POLICY/xccdf_policy_remediate.c (hunk 1 above)
Comment (jan-cerny) [reply src/XCCDF_POLICY/xccdf_policy_remediate.c]: This function would be a perfect candidate for an unit test!

File: src/XCCDF_POLICY/xccdf_policy_remediate.c (hunk 4 above)
Comment (jan-cerny) [reply src/XCCDF_POLICY/xccdf_policy_remediate.c]: It doesn't seem resuable to me because there is multiple assumptions (size of the buffer, size of the filler, size of the token, index of the token).

Comment (matejak) [reply src/XCCDF_POLICY/xccdf_policy_remediate.c]: It may not be reusable, but it would decrease the cognitive complexity of the code. If you are against an extraction, then put a comment there.

File: src/XCCDF_POLICY/xccdf_policy_remediate.c (hunk 1 above)
Comment (matejak) [reply src/XCCDF_POLICY/xccdf_policy_remediate.c]: Yes. and I think that you can rename it to `trim_trailing_whitespace` or `rstrip`, as  multiline comments are out of scope of this function.

File: src/XCCDF_POLICY/xccdf_policy_remediate.c [hunk 5]
```diff
@@ -802,6 +802,72 @@ static int _xccdf_item_recursive_gather_selected_rules(struct xccdf_policy *poli
 	return ret;
 }
 
+static void _comment_multiline_text_strip_trailing_whitespace(char *token, size_t token_len)
```
Comment (matejak) [inline src/XCCDF_POLICY/xccdf_policy_remediate.c]: I think that you can rename this one to `trim_trailing_whitespace` or `rstrip`, as multiline comments are out of scope of this function.

File: src/XCCDF_POLICY/xccdf_policy_remediate.c (hunk 4 above)
Comment (jan-cerny) [reply src/XCCDF_POLICY/xccdf_policy_remediate.c]: I think we can survive coding normally it this case. We don't need to create lot of pointers if we are not going to use the code again.

File: src/XCCDF_POLICY/xccdf_policy_remediate.c (hunk 5 above)
Comment (jan-cerny) [reply src/XCCDF_POLICY/xccdf_policy_remediate.c]: OK

**Comment by jan-cerny** [comment]
@matejak I have renamed the static function which removes the trailing whitespace to just `_trim_trailing_whitespace`.

However, I haven't found any nice function to extract from the `_comment_multiline_text`.

File: src/XCCDF_POLICY/xccdf_policy_remediate.c (hunk 4 above)
Comment (matejak) [reply src/XCCDF_POLICY/xccdf_policy_remediate.c]: OK, may be.

File: src/XCCDF_POLICY/xccdf_policy_remediate.c [hunk 6]
```diff
@@ -802,6 +802,72 @@ static int _xccdf_item_recursive_gather_selected_rules(struct xccdf_policy *poli
...
+		if (token == NULL) {
+			break;
+		}
+		/* Strip leading whitespace */
+		while (isspace(*token)) {
+			token++;
+		}
+		size_t token_len = strlen(token);
+		if (token_len > 0) {
+			/* Strip trailing whitespace */
```
Comment (matejak) [inline src/XCCDF_POLICY/xccdf_policy_remediate.c]: Pleare remove that comment - it is not needed, as you have introduced the `_trim_trailing_whitespace` function, so it is now obvious what is going on.

**Comment by matejak** [comment]
@jan-cerny The PR is basically good to merge. If you have time, please remove a redundant comment.

**Comment by matejak** [comment]
Thank you for the PR!
